name: Checkout new PR
on:
  pull_request_target:
jobs:
  Checkout_PR_and_run_tests:
    runs-on: ubuntu-18.04
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
      - name: PR checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit }}

      - name: save the ssh key for access to robot to the file
        run: 'echo "$SSH_KEY" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }}
      - run: chmod 400 the_key
      - name: Log into stretch using ssh and run tests
        run: ssh -i the_key hello-robot@"${STRETCH_IP}" -p "$STRETCH_PORT" -tt -o StrictHostKeyChecking=no < ./.github/workflows/ssh_commands_test.sh
        env:
          STRETCH_IP: 72.134.86.243
          STRETCH_PORT: 43771