name: Checkout new PR
on:
  pull_request_target:
jobs:
  Checkout_PR_and_run_tests:
    runs-on: ubuntu-18.04
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
      - name: PR checkout
        uses: actions/checkout@v2

      - name: save the ssh key for access to robot to the file
        run: 'echo "$SSH_KEY" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }}
      - run: chmod 400 the_key
      - run: touch ssh_commands_pr_info.sh
      - name: Replace PR number
        run: sed "s/\$pr_number/${PR_NUMBER}/" ./.github/workflows/pr_checkout_commands.sh > ssh_commands_pr_info.sh
        env:
          PR_NUMBER: 6
      - name: Replace branch name
        run: sed "s/\$branch_name/${BRANCH_NAME}/" ssh_commands_pr_info.sh > ssh_commands_pr_info.sh
        env:
          BRANCH_NAME: direct_PR_access
      - run: cat ssh_commands_pr_info.sh
      - name: Log into stretch using ssh and run tests
        run: ssh -i the_key hello-robot@"${STRETCH_IP}" -p "$STRETCH_PORT" -tt -o StrictHostKeyChecking=no < ./ssh_commands_pr_info.sh
        env:
          STRETCH_IP: 72.134.86.243
          STRETCH_PORT: 43771