name: run unit tests
on: 
  pull_request:
    branches:
      - feature/git_action_test
jobs:
  ssh-connection-teleop:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: save the ssh key for access to robot to the file
        run: 'echo "$SSH_KEY" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }}
          STRETCH_IP: 72.134.86.243
          STRETCH_PORT: 43771
      - run: chmod 400 the_key
      - name: Log into stretch using ssh and run tests
        run: ssh -i the_key hello-robot@$STRETCH_IP -p $STRETCH_PORT -tt -o StrictHostKeyChecking=no < ./.github/workflows/ssh_commands_test.sh
